# Configuration for Directly Closing Threads - https://github.com/marketplace/actions/stale

name: 'Close Issues'
on:
  workflow_dispatch:
  schedule:
    - cron: '12 12 * * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:

      - name: Close Duplicate Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item has been closed as a known issue.
          days-before-stale: 1
          days-before-close: 2
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Flagged'
          any-of-issue-labels: 'Duplicate,Known-Issue'

      - name: Close Invalid Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item has been closed as the issue could not be replicated.
          days-before-stale: 1
          days-before-close: 2
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Flagged'
          any-of-issue-labels: 'Invalid,Works-For-Me'

      - name: Close WontFix Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item has been closed as a fix will not be attempted.
          days-before-stale: 1
          days-before-close: 2
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Flagged'
          only-issue-labels: 'WontFix'
