name: 'Issues'

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID'
        required: true
        default: 'all'
  issues:
    types: [opened, reopened, closed]
  schedule:
    - cron: '4 4 */4 * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Add Labels - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_open:
    name: Default Issue Label
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && github.actor != 'dakanji' && github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Pending

  add_label_user_open_enhance:
    name: Enhancement Request Label
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && github.event_name == 'issues' && github.event.action == 'opened' && ${{ startsWith(github.event.comment.body, 'Suggested Feature') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Enhancement

  add_label_user_close:
    name: Close Issue Label
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && github.actor != 'dakanji' && github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Cancelled

  # Del Labels - https://github.com/dessant/label-actions
  del_label_user_reopen:
    name: Remove Cancelled Label
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && github.actor != 'dakanji' && github.event_name == 'issues' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ github.token }}
          labels: Cancelled

  del_label_user_close:
    name: Remove Pending Label
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ github.token }}
          labels: Pending

  # Handle Stale Threads - https://github.com/actions/stale
  stale:
    name: Flag or Close Issues
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && (github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'stale')
    steps:

      - name: Close Resolved Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: ''
          stale-issue-label: 'Tagged'
          any-of-labels: 'Resolved'

      - name: Flag or Close Incomplete Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to missing required information.
          close-issue-message: >
            This item is being closed due to missing required information.
          days-before-stale: 0
          days-before-close: 4
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Incomplete, Unclear'

      - name: Flag or Close No-Response Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to a lack of response.
          close-issue-message: >
            This item is being closed due to a lack of response.
          days-before-stale: 4
          days-before-close: 4
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Queries'

      - name: Flag or Close Inactive Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 20
          days-before-close: 8
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          exempt-issue-labels: 'Parked, Help-Wanted'

      - name: Flag or Close Parked Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 60
          days-before-close: 28
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          any-of-labels: 'Parked'

      - name: Flag or Close Parked Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 120
          days-before-close: 60
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Help-Wanted'

      - name: Close Duplicate Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as a known issue.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Duplicate, Known-Issue'

      - name: Close Invalid Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as the issue could not be replicated.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Invalid, Works-For-Me'

      - name: Close WontFix Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as a fix will not be attempted.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'WontFix'

      - name: Catchall Closer
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as abandoned.
          days-before-stale: 180
          days-before-close: 180
          stale-issue-label: 'Tagged'

  # Lock Threads - https://github.com/dessant/lock-threads
  lock:
    name: Lock Threads
    needs: stale
    runs-on: ubuntu-latest

    if: github.repository_owner == 'dakanji' && (github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'lock')
    steps:

      - name: Lock Incomplete Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Incomplete, Unclear'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Duplicate Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '1'
          include-any-issue-labels: 'Duplicate, Known-Issue'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock WontFix Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          issue-inactive-days: '1'
          include-any-issue-labels: 'WontFix'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Invalid Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '1'
          include-any-issue-labels: 'Invalid, Works-For-Me'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Resolved Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          issue-comment: >
            This specific item has resolved. Please create a new issue if the item persists or use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature to discuss related items.
          issue-inactive-days: '1'
          include-any-issue-labels: 'Resolved'
          exclude-any-issue-labels: 'Parked, Help-Wanted'
          add-issue-labels: ''
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Inactive Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '3'
          include-any-issue-labels: ''
          exclude-any-issue-labels: 'Parked, Help-Wanted'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'
