name: 'Issue Labels'

on:
  issues:
    types: [opened, reopened, closed]

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Add Labels - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_open:
    name: Default Issue Label
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Pending

  add_label_user_open_enhance:
    name: Enhancement Request Label
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' && startsWith(github.event.comment.body, '### Suggested Feature') && contains(github.event.comment.body, '### Background Information')
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Enhancement

  add_label_user_close:
    name: Close Issue Label
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: Cancelled

  # Del Labels - https://github.com/dessant/label-actions
  del_label_user_reopen:
    name: Remove Cancelled Label
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ github.token }}
          labels: Cancelled

  del_label_user_close:
    name: Remove Pending Label
    runs-on: ubuntu-latest

    if: github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          github_token: ${{ github.token }}
          labels: Pending
