# Configuration for Handling Stale Threads - https://github.com/marketplace/actions/stale

name: 'Handle Stale Issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 * * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:

      - name: Stale Incomplete Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to missing required information.
          days-before-stale: 1
          days-before-close: 2
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Flagged'
          any-of-issue-labels: 'Incomplete,Unclear'

      - name: Stale No-Response Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to a lack of response.
          days-before-stale: 7
          days-before-close: 7
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Flagged'
          any-of-issue-labels: 'Queries'

      - name: Stale Inactive Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          days-before-stale: 21
          days-before-close: 7
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          exempt-issue-labels: 'Parked'

      - name: Stale Parked Issues
        uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          days-before-stale: 60
          days-before-close: 30
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          only-issue-labels: 'Parked'
